version: '3'
services:

  app_python:
    image: mkhalil99/py_app:latest
    expose:
      - 8000
    ports:
      - 8000:8000
#    command: ["--log-level", "debug"]
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}"

  app_react:
    image: mkhalil99/react_app:latest
    expose:
      - 5000
    ports:
      - 5000:5000
#    command: ["--log-level", "debug"]
    logging:
      driver: json-file
      options:
        tag: "{{.ImageName}}|{{.Name}}"

  loki:
    image: grafana/loki:2.6.1
    expose:
      - 3100
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml

  promtail:
    image: grafana/promtail:2.6.1
    expose:
      - 9080
    ports:
      - "9080:9080"
    volumes:
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - promtail-data:/var/lib/promtail/positions
      - ${PWD}/promtail.yml:/etc/promtail/promtail.yml
    command: -config.file=/etc/promtail/promtail.yml
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ${PWD}/loki.yml:/etc/grafana/provisioning/datasources/datasource.yml
    environment:
      - GF_PATHS_PROVISIONING=/etc/grafana/provisioning
    expose:
      - 3000
    ports:
      - "3000:3000"

volumes:
  promtail-data: {}
